### ISSUE TITLE
Large playlists cause a freeze

### ISSUE THREAD

**Issue by simonzsh** [distubejs/spotify#14]
**Please describe your problem in as much detail as possible:**
When I try to play a large spotify playlist (600 songs), it causes my bot to freeze due to a large CPU increase.
I think it would be nice to be able to set a limit of songs you take so the bot doesn't have to load everything.

**Further information:**

- Plugin version: 1.0.0
- DisTube version: 3.0.3
- discord.js version: 13.3.1
- Node.js version: 16.11.1
- Operating system: Microsoft Windows 11

**Comment by skick1234** [comment]
Set `parallel` option to false for low performance specs
