### ISSUE TITLE
No result found when using <DisTube>.search() method on a Spotify link!

### ISSUE THREAD

**Issue by Majoramari** [distubejs/spotify#15]
**Please describe your problem in as much detail as possible:**

The Distube options: 
```js
{
            updateYouTubeDL: false,
            youtubeCookie: this.settings.main.cookie,
            searchSongs: 10,
            emitNewSongOnly: true,
            leaveOnStop: false,
            plugins: [new SpotifyPlugin(), new SoundCloudPlugin()],
}
```

Error Message:
```
DisTubeError [NO_RESULT]: No result found
    at DisTube.search (C:\Users\Major\Documents\github\Rayila\node_modules\distube\src\DisTube.ts:329:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[ERROR] 11:46:45 DisTubeError [NO_RESULT]: No result found
```

**⚠️ NOTE: After some testing I think the issue with `<DisTube>.search();` because `<DisTube>.playVoiceChannel();` is working fine...**

**Further information:**

- Plugin version: 1.0.0
- DisTube version: 3.0.3
- discord.js version: 13.3.1
- Node.js version: 16.6.1
- Operating system: Windows 11 21h1 Build 22000

**Comment by LackyPal** [comment]
Read the docs
You have added Spotify plugin, so if you want play Spotify links just use `<DisTube>.playVoiceChannel()` or `<DisTube>.play()` method.
`<DisTube>.search()` method require a search string to search videos or playlist on YouTube. When you search using a Spotify links, it's obvious there is no result for that link on YouTube. If you want to search on Spotify use some other package
