### ISSUE TITLE
The package doesen't work!

### ISSUE THREAD

**Issue by peter00704** [distubejs/spotify#16]
**I got this error:**
postinstall:container: timing audit body Completed in 1m /home/container/node_modules/@distube/spotify/dist/index.js:44
class SpotifyPlugin extends distube_1.CustomPlugin {
TypeError: Class exten

**Further information:**

- Plugin version:1.1.0
- DisTube version:2.8.15
- discord.js version:12.5.3
- Node.js version:12
- Operating system:windows

**Comment by skick1234** [comment]
v2 doesn't support plugin
