### ISSUE TITLE
Large playlists cause a freeze

### ISSUE THREAD

**Issue by simonzsh** [distubejs/spotify#17]
**Please describe your problem in as much detail as possible:**
When I play a large spotify playlist, my bot's voice freezes.
I don't understand why there is this problem since my bot does not exceed its CPU limit (it has 4 cores).
I wish I didn't have this problem without having to set the `parallel` option to false because otherwise it is too slow to search.
![unknown](https://user-images.githubusercontent.com/65893656/154336873-57d02a83-861f-45ed-aeab-02530ad996eb.png)

**Further information:**
Plugin version: 1.2.1
DisTube version: 3.3.2
discord.js version: 13.6.0
Node.js version: 16.13.2
Operating system: Microsoft Windows 11

**Comment by skick1234** [comment]
But you have to do it :> And maybe it related to your network connection

**Comment by simonzsh** [comment]
No there is no problem with my network connection
