### ISSUE TITLE
DeprecationWarning error

### ISSUE THREAD

**Issue by flyflow84** [distubejs/spotify#20]
Hi,
I am facing this problem, anyone have an idea to solve it?

```
(node:13632) DeprecationWarning: Passing Message for DisTube#play is deprecated, use BaseGuildVoiceChannel instead.
```
![Capture](https://user-images.githubusercontent.com/76762960/207823339-3b9f05c0-3d34-4ae5-940e-32c90f26328c.JPG)
![capture1](https://user-images.githubusercontent.com/76762960/207823344-394e6690-c0bd-49e8-81fa-96e8495dc184.JPG)

Node : v19
Discord : v12
Distube : v3

**Comment by skick1234** [comment]
Not related to this package
