### ISSUE TITLE
if (track.type !== "track") Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by Tduck5819** [distubejs/spotify#22]
When i add a playlist to the queue i will get this error

/home/tijmen/musicadev/node_modules/@distube/spotify/dist/index.js:280
        if (track.type !== "track")
                  ^

TypeError [PlayError]: https://open.spotify.com/playlist/6nOdNZWcNjURpp2lcMvjDU?si=f9920966151f4e47
Cannot read properties of null (reading 'type')
    at /home/tijmen/musicadev/node_modules/@distube/spotify/dist/index.js:280:19
    at Array.map (<anonymous>)
    at SpotifyPlugin.play (/home/tijmen/musicadev/node_modules/@distube/spotify/dist/index.js:279:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DisTube.play (/home/tijmen/musicadev/node_modules/distube/dist/index.js:2264:13)

Node.js v18.12.1

**Further information:**

- Plugin version: 1.5.0
- DisTube version: 4.0.4
- discord.js version: 14.7.1
- Node.js version: 18.12.1
- Operating system: Ubuntu 22.04.1 LTS

**Comment by skick1234** [comment]
Due to the link is private or unavailable. Spotify changed the response that why it doesn't throw an valid error. So it not really a bug, just an unclear error.

**Comment by Tduck5819** [comment]
but in the previous version with the same playlist there where no errors

**Comment by skick1234** [comment]
I see, the site are changing their response recently that why it's become unavailable. I will investigate and update it when I have my pc back.
