### ISSUE TITLE
Spotify music link that does not work

### ISSUE THREAD

**Issue by byorage** [distubejs/spotify#24]
**Please describe your problem in as much detail as possible:**
when I launch a music and in the music link the link contains "intl-fr" the bot does not find the music and therefore does not play it.
example link: https://open.spotify.com/intl-fr/track/0HYaC4uGgpx7EIBekhxWfi?si=3d5289545af74ea2

**Further information:**

- Plugin version: 1.5.1
- DisTube version: 4.0.6
- discord.js version: 14.13.0
- Node.js version: 18.x
- Operating system: Server Linux

**Comment by skick1234** [comment]
All redirect links won't be supported since we cannot handle all of them.
Just follow redirects then play the final location instead.

**Comment by Akif9748** [comment]
A basic solution for now:
```js
// Input URLs
const inputURL = "https://open.spotify.com/intl-fr/track/0HYaC4uGgpx7EIBekhxWfi?si=3d5289545af74ea2";

// Define a regular expression to match and remove the '/intl-xx/' part from the URLs
const regex = /\/intl-[a-z]{2}\//;

// Replace the matching part with an empty string
const outputURL= inputURL.replace(regex, '/');

// Output converted URL
console.log(outputURL);

 ```
