### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by octagonemusic** [distubejs/spotify#4]
My console always gives me this error:

  if (Array.isArray(queue.songs) && queue.songs[0]?.streamURL) resolve(clearInterval(check));
                                                             ^

SyntaxError: Unexpected token '.'

this error is in the index.js of this plugin

**Comment by skick1234** [comment]
Due to your nodejs is not supported optional chaining (?.)

Distube v3 required it (nodejs v14 or higher)
