### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by iiAlanii** [distubejs/spotify#8]
if (Array.isArray(queue.songs) && queue.songs[0]?.streamURL) resolve(clearInterval(check));
                                                                                 ^
![Screenshot 2021-07-07 132654](https://user-images.githubusercontent.com/85262775/124751535-06754780-df27-11eb-932c-3c19c1184809.gif)

**Comment by skick1234** [comment]
Beta plugin require nodejs v14
